language: node_js

node_js:
  - "8"

before_install:
  - export PATH=$PATH:$HOME/.local/bin

install:
  - travis_retry npm install

script:
  - set -e
  - npm run eslint
  - npm run jsinspect
  - npm test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3c87287517b9672eb7d9
    on_success: change
    on_failure: always
    on_start: never

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
