language: node_js

node_js:
  - "6"

services:
  - docker

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - travis encrypt aws_access_key_id=$aws_access_key_id --add --override
  - travis encrypt aws_secret_access_key=$aws_secret_access_key --add --override

install:
  - travis_retry npm install

script:
  - npm run eslint
  - npm run jsinspect
  - aws configure --profile squeezer-test set aws_access_key_id $aws_access_key_id
  - aws configure --profile squeezer-test set aws_secret_access_key $aws_secret_access_key
  - aws configure --profile squeezer-test set region us-east-1
  - ls -al $HOME/.aws
  - cat $HOME/.aws/credentials
  - cat $HOME/.aws/config
  - npm run test-units
  - npm run test-integration
